### ISSUE TITLE
Error when importing the feed into Bamboo

### ISSUE THREAD

**Issue by EinfachToll** [VimFeed/VimFeed#1]
I'm using a Firefox addon called [Bamboo](https://addons.mozilla.org/de/firefox/addon/bamboo-feed-reader/?src=search) to read my RSS and Atom feeds. But when I try to import this feed, I get an error (which I somehow can't copy and paste, so here is a screenshot).

The first line roughly says in English: Reading failed: Illegal format

The second line: XML processing error: not defined entity

The start of the fourth line: Line no. 1881, column 3: …

![2016-10-15-175241_1268x337_scrot](https://cloud.githubusercontent.com/assets/585537/19411370/cb5568d2-9300-11e6-8398-2e9ecaab6fd1.png)
![2016-10-15-175256_1278x320_scrot](https://cloud.githubusercontent.com/assets/585537/19411371/cb58dc2e-9300-11e6-888a-7be27f6d95a6.png)

I hope you can make sense of it, because I can't ;)

**Comment by nkantar** [comment]
Alrighty, I'll see what I can do. Thanks for the issue report!

**Comment by nkantar** [comment]
@EinfachToll The feed is now completely different, so would you mind trying again and letting me know if this is still an issue? Thanks!

**Comment by EinfachToll** [comment]
@nkantar No more errors :+1:
