### ISSUE TITLE
Damaged mobile-friendly stylesheets

### ISSUE THREAD

**Issue by Kutsan** [VimFeed/VimFeed#2]
![](https://i.imgur.com/4kNdidi.png)

**Comment by nkantar** [comment]
That does indeed look a bit wonky. Thanks for the bug report!

**Comment by nkantar** [comment]
@Kutsan The feed is now completely different, so would you mind trying again and letting me know if this is still an issue? Thanks!

**Comment by Kutsan** [comment]
@nkantar Yup, now it's good.
Also, as a personal suggestion you should use Menlo font as main font. It's more fits the concept.

**Comment by nkantar** [comment]
I stayed away from monospaced typefaces when the feed included full-text content, so now it's due for a redesign anyway. :thumbsup:
